language: python

python:
  - "2.7"

install:
  - "pip install -r requirements.txt"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then find . -name '*.py' | xargs 2to3 -wn fi"

script: nosetests

notifications:
  email:
    - nineseconds@yandex.ru