language: python

python:
  - "2.7"
  # nltk does not support python3 yet
  # - "3.3"

install:
  - "pip install -r requirements.txt"
  - "python setup.py install"

script: nosetests

notifications:
  email:
    - nineseconds@yandex.ru